### ISSUE TITLE
Escape Key freeze While Selenium test is running

### ISSUE THREAD

**Issue by zaka786khan** [florentbr/SeleniumBasic#55] opened 2016-01-04 04:44 UTC
Hi Dear florentbr!

Just noticed that when SeleniumBasic 2.0.6 tests are run the escape key of keyboard does not work. While trying pressing escape too many times selenium gives error such like KeyError. 
It seems Selenium blocks Escape key or keep in its use and for other applications Escape key does not work. Please check this issue.

**Comment by florentbr** [comment] 2016-01-06 13:52
Duplicate of #43

**Closed by florentbr** 2016-01-06 13:52 UTC
