### ISSUE TITLE
VBScript runtime error: ActiveX component can't create object: 'Selenium.ChromeDriver'

### ISSUE THREAD

**Issue by shawnmkelly** [florentbr/SeleniumBasic#14] opened 2015-08-26 04:55 UTC
First, thank you for all you do.

I'm trying the sample vbs scripts and receive the following error

c:\Users\shawn\temp>"DownloadFile(Chrome).vbs"
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\shawn\temp\DownloadFile(Chrome).vbs(12, 3) Microsoft VBScript runtime error: ActiveX component can't create object: 'Selenium.ChromeDriver'

Click OK to close the browser
C:\Users\shawn\temp\DownloadFile(Chrome).vbs(23, 3) Microsoft VBScript runtime error: Object required: 'driver'

What's interesting is the Excel examples work fine.

I've tried registering the selenium.dll with both regasm and regsrv32 without success.

I'd be grateful for any insight.

Thank you.

**Comment by florentbr** [comment] 2015-08-26 08:55
Is it working when running the file with the context menu Open?
Are you running your console under the current user or under admin?

Can you check if these registry keys are present:
HKEY_CURRENT_USER\Software\Classes\Selenium.ChromeDriver
HKEY_CURRENT_USER\Software\Classes\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E8C9}
HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E8C9}

**Comment by shawnmkelly** [comment] 2015-08-26 12:17
Thanks for the quick reply.

 

It does not work with the file context menu.

It does not work under admin.

 

Here are reg entries:

 

Windows Registry Editor Version 5.00

 

[HKEY_CURRENT_USER\Software\Classes\Selenium.ChromeDriver]

@="Selenium.ChromeDriver"

 

[HKEY_CURRENT_USER\Software\Classes\Selenium.ChromeDriver\CLSID]

@="{0277FC34-FD1B-4616-BB19-5D556733E8C9}"

 

Windows Registry Editor Version 5.00

 

[HKEY_CURRENT_USER\Software\Classes\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E
8C9}]

@="Selenium.ChromeDriver"

 

[HKEY_CURRENT_USER\Software\Classes\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E
8C9}\Implemented Categories]

 

[HKEY_CURRENT_USER\Software\Classes\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E
8C9}\Implemented Categories\{62C8FE65-4EBB-45e7-B440-6E39B2CDBF29}]

@=""

 

[HKEY_CURRENT_USER\Software\Classes\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E
8C9}\InprocServer32]

@="mscoree.dll"

"Class"="Selenium.ChromeDriver"

"Assembly"="Selenium, Version=2.0.4.0, Culture=neutral,
PublicKeyToken=d499ab7f7ba4d827"

"RuntimeVersion"="v2.0.50727"

"CodeBase"="C:\\Users\\shawn\\AppData\\Local\\SeleniumBasic\\Selenium.dll"

"ThreadingModel"="Both"

 

[HKEY_CURRENT_USER\Software\Classes\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E
8C9}\ProgId]

@="Selenium.ChromeDriver"

 

[HKEY_CURRENT_USER\Software\Classes\CLSID\{0277FC34-FD1B-4616-BB19-5D556733E
8C9}\VersionIndependentProgID]

@="Selenium.ChromeDriver"

 

 

 

Windows Registry Editor Version 5.00

 

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{0277FC34-FD1B-4616-BB
19-5D556733E8C9}]

@="Selenium.ChromeDriver"

 

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{0277FC34-FD1B-4616-BB
19-5D556733E8C9}\Implemented Categories]

 

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{0277FC34-FD1B-4616-BB
19-5D556733E8C9}\Implemented
Categories\{62C8FE65-4EBB-45e7-B440-6E39B2CDBF29}]

@=""

 

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{0277FC34-FD1B-4616-BB
19-5D556733E8C9}\InprocServer32]

@="C:\\Windows\\SysWOW64\\mscoree.dll"

"Class"="Selenium.ChromeDriver"

"Assembly"="Selenium, Version=2.0.4.0, Culture=neutral,
PublicKeyToken=d499ab7f7ba4d827"

"RuntimeVersion"="v2.0.50727"

"CodeBase"="C:\\Users\\shawn\\AppData\\Local\\SeleniumBasic\\Selenium.dll"

"ThreadingModel"="Both"

 

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{0277FC34-FD1B-4616-BB
19-5D556733E8C9}\ProgId]

@="Selenium.ChromeDriver"

 

[HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{0277FC34-FD1B-4616-BB
19-5D556733E8C9}\VersionIndependentProgID]

@="Selenium.ChromeDriver"

**Comment by florentbr** [comment] 2015-08-26 16:17
Which version of windows do you use?
The library looks correctly regitered.
It could be that you are not running the script under the same account as the one that was used to install it.
It won't work if the script is exectued as admin since the library is registred only for the current user.

Could you try these commands in the Run dialog (Win+R):

    C:\Windows\System32\WScript.exe "%USERPROFILE%\AppData\Local\SeleniumBasic\Scripts\StartChrome.vbs"
    C:\Windows\SysWow64\WScript.exe "%USERPROFILE%\AppData\Local\SeleniumBasic\Scripts\StartChrome.vbs"

Could you also try to run this alternative VBScript:

    Set driver = GetObject("new:{0277FC34-FD1B-4616-BB19-5D556733E8C9}")
    driver.Start
    WScript.Echo "OK"
    driver.Quit


Utlimately you could force the registration for all users:

To unregister, run all the following lines as admin (Win+X+A):

    cd %USERPROFILE%\AppData\Local\SeleniumBasic
    C:\Windows\Microsoft.NET\Framework64\v2.0.50727\regasm.exe Selenium.dll /codebase /tlb:Selenium64.tlb /unregister
    C:\Windows\Microsoft.NET\Framework\v2.0.50727\regasm.exe Selenium.dll /codebase /tlb:Selenium32.tlb /unregister
    del *.tlb

To register, run all the following lines as admin (Win+X+A):

    cd %USERPROFILE%\AppData\Local\SeleniumBasic
    C:\Windows\Microsoft.NET\Framework64\v2.0.50727\regasm.exe Selenium.dll /codebase /tlb:Selenium64.tlb
    C:\Windows\Microsoft.NET\Framework\v2.0.50727\regasm.exe Selenium.dll /codebase /tlb:Selenium32.tlb

**Comment by shawnmkelly** [comment] 2015-08-27 03:07
Windows 7

 

I forced reregistration. Now, all command tries result in is the error
depicted below with the dreaded "He's dead Jim". I reset Chrome setting to
try to clear the issue and loaded the latest version of chromedriver to no
availe. Automation through Excel continues to work correctly.

**Comment by shawnmkelly** [comment] 2015-08-27 03:53
It seems others are have similar issues:
https://code.google.com/p/chromium/issues/detail?id=514084#c17

 

 

From: Shawn Kelly [mailto:shawnmkelly@verizon.net] 
Sent: Wednesday, August 26, 2015 11:08 PM
To: 'florentbr/SeleniumBasic'
<reply+00cd062957aafbc93ac67da36fc00c9455b32a5e4413d06f92cf0000000111f5a89b9
2a169ce06265174@reply.github.com>; 'florentbr/SeleniumBasic'
<SeleniumBasic@noreply.github.com>
Subject: RE: [SeleniumBasic] VBScript runtime error: ActiveX component can't
create object: 'Selenium.ChromeDriver' (#14)

 

Windows 7

 

I forced reregistration. Now, all command tries result in is the error
depicted below with the dreaded "He's dead Jim". I reset Chrome setting to
try to clear the issue and loaded the latest version of chromedriver to no
availe. Automation through Excel continues to work correctly.

**Comment by shawnmkelly** [comment] 2015-08-27 04:06
Based on this thread:
https://productforums.google.com/forum/#!msg/chrome/TO8-9P_AQvc/3lQA5ZZ-neAJ

 

And using this script:

Set driver = CreateObject("Selenium.ChromeDriver")

driver.AddArgument ("--disable-appcontainer")

driver.Start

WScript.Echo "Click OK to quit"

driver.Quit

 

Got the same error

 

From: Shawn Kelly [mailto:shawnmkelly@verizon.net] 
Sent: Wednesday, August 26, 2015 11:53 PM
To: 'florentbr/SeleniumBasic'
<reply+00cd062957aafbc93ac67da36fc00c9455b32a5e4413d06f92cf0000000111f5a89b9
2a169ce06265174@reply.github.com>; 'florentbr/SeleniumBasic'
<SeleniumBasic@noreply.github.com>
Subject: RE: [SeleniumBasic] VBScript runtime error: ActiveX component can't
create object: 'Selenium.ChromeDriver' (#14)

 

It seems others are have similar issues:
https://code.google.com/p/chromium/issues/detail?id=514084#c17

 

 

From: Shawn Kelly [mailto:shawnmkelly@verizon.net] 
Sent: Wednesday, August 26, 2015 11:08 PM
To: 'florentbr/SeleniumBasic'
<reply+00cd062957aafbc93ac67da36fc00c9455b32a5e4413d06f92cf0000000111f5a89b9
2a169ce06265174@reply.github.com>; 'florentbr/SeleniumBasic'
<SeleniumBasic@noreply.github.com>
Subject: RE: [SeleniumBasic] VBScript runtime error: ActiveX component can't
create object: 'Selenium.ChromeDriver' (#14)

 

Windows 7

 

I forced reregistration. Now, all command tries result in is the error
depicted below with the dreaded "He's dead Jim". I reset Chrome setting to
try to clear the issue and loaded the latest version of chromedriver to no
availe. Automation through Excel continues to work correctly.

**Comment by florentbr** [comment] 2015-08-29 07:23
I've just tested it on a clean user session on Windows 7 64bit.

Regarding the crach of Chrome ("He's dead Jim"), I was able to reproduce it.
It will be fixed in the next release (2.0.5.0)

Regarding the error "ActiveX component can't create object", I wasn't able to reproduce it.
This means that something on your station must be interfering or that your registration is somehow corrupted. You should try to clean your registry and then try to reinstall.
Here is a cmd script to remove all the SeleniumBasic keys:

    @echo off
    
    set f=%TEMP%\reglist.txt
    IF EXIST %f% del /F %f%
    
    REG QUERY HKLM\Software\Classes /f "Selenium." /k /s >>%f%
    REG QUERY HKCU\Software\Classes /f "Selenium." /k /s >>%f%
    REG QUERY HKLM\SOFTWARE\Classes /f "{0277FC34-FD1B-4616-BB19" /k /s >>%f%
    REG QUERY HKCU\SOFTWARE\Classes /f "{0277FC34-FD1B-4616-BB19" /k /s >>%f%
    
    setlocal enableextensions enabledelayedexpansion
    for /f "tokens=*" %%a in (%f%) do (
        Set line=%%a
        if "!line:~,5!"=="HKEY_" (
            echo !line!
            REG DELETE !line! /f
        )
    )
    endlocal

Note that it should be executed as user and as admin

**Comment by shawnmkelly** [comment] 2015-09-03 01:18
Tempory Solution:

Based upon this thread: https://github.com/FuckTheWorld/chromedriver/issues/539

I tried the driver.AddArgument ("--no-sandbox")

Both VBS and  XLS are now working as expected. I'm not familiar with what --no-sandbox does for me one way or another, but at least I have my scripts working again.

Thanks much for your responsiveness to my issue.

**Comment by florentbr** [comment] 2015-09-09 11:57
Fixed in v2.0.5.0

**Closed by florentbr** 2015-09-09 11:57 UTC
